# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - node -e "console.log(v8.getHeapStatistics().heap_size_limit)"
      - node -e "console.log(v8.getHeapStatistics().total_heap_size)"
      - node -e "console.log(v8.getHeapStatistics().used_heap_size)"
      - npm install
  build:
    commands:
      - echo Running Tests
      - npm test
      - node -e "console.log(v8.getHeapStatistics().total_heap_size/)"
      - node -e "console.log(v8.getHeapStatistics().used_heap_size/)"
  post_build:
    commands:
      - echo Tests Complete
