# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - node -e "console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))"
      - npm install
  build:
    commands:
      - node -e "console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))"
      - echo Running Tests
      - npm test
  post_build:
    commands:
      - node -e "console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))"
      - echo Tests Complete
